notification_settings:
    smtp_server: 'smtp.example.com'
    from_address: 'netapp_replication_report@example.com'
    to_address: 'user@example.com, user2@example.com'
    subject: "NetApp volume replication report"

netapp_controllers:
    filer1:
        user: root
        pw: root
        ignore_volumes:
            - vol0
    filer2:
        user: user1
        pw: secret
